version: 2

sources:

  - name: ruggable
    database: first-project-262802
    schema: ruggable
    tables:
      - name: raw_rugs_usa_category_map
      - name: raw_rugs_usa_color_map
      - name: raw_rugs_usa_links
      - name: raw_rugs_usa_pads_upsell
      - name: raw_rugs_usa_parent
      - name: raw_rugs_usa_variant
      