version: 2

sources:

  - name: stock
    database: first-project-262802
    schema: stock
    tables:
      - name: 400_years_of_generated_dates_and_holidays

      - name: all_nasdaq_stock_history

      - name: all_others_stock_history

      - name: polygon_all_different_stock_histories_1m_etl_date_2025_04_17

      - name: polygon_all_different_stock_histories_1m_elt_date_2025_06_09

      - name: buy_sell_personal_backtesting_1m_consolidated_detailed

      - name: buy_sell_personal_backtesting_1m_consolidated_summary_overall

      - name: buy_sell_personal_backtesting_1m_consolidated_summary_per_trade
      
